# Generated by Django 5.1.7 on 2025-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Цена за ночь'),
            preserve_default=False,
        ),
    ]
